name: Rene Becker Medical Athlete Coach
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e8b0f772-67e4-40f9-adcc-9cd1407145c7.false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/67410cc4-0902-4a1b-b2ab-10117f5a43b2.png
layout_spectrum: 0.6703945547487993
typography_spectrum: 0.5232461857685985
analytics:
  twitter: Herr
opengraph:
  type: primefit121
  appId: 'https://www.facebook.com/primefit121/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/faf835e1-ffec-489c-b494-6d0bf6a8ca47.jpg
color:
  brandColors:
    - '#FFFFFF'
    - '#0E0E0E'
    - '#ECD5B6'
    - '#9D9389'
    - '#675D54'
  brandStrength: 0.2763802294829621
  lightness: 0.49772342530752317
  saturation: 0.6156634264338835
  rhythmicContrast: 0.15419527996276128
purpose:
  - type: contact
    label: E-Mail me
    url: 'mailto:rbecker@prime-fit-121.de'
  - type: external
    label: Facebook
    url: 'https://www.facebook.com/primefit121/'
title: Medical Training/Athleten Coaching
description: Beseitigung von Dysbalancen orthopädischer Natur
author:
  name: Rene Becker
  email: rbprivattraining@gmail.com
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
