name: PrimeFit
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/63aa34cf-9654-4cf6-b4a7-44c935b116e7.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d29573cd-33bc-4353-8131-be4143eb00a0.jpg
layout_spectrum: 0.6703945547487993
typography_spectrum: 0.5232461857685985
analytics:
  twitter: Herr
opengraph:
  type: Medical Fitness
  appId: 'https://www.facebook.com/primefit121/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/faf835e1-ffec-489c-b494-6d0bf6a8ca47.jpg
color:
  brandColors:
    - '#FFFFFF'
    - '#0E0E0E'
    - '#ECD5B6'
    - '#9D9389'
    - '#675D54'
  brandStrength: 0.2763802294829621
  lightness: 0.49772342530752317
  saturation: 0.6156634264338835
  rhythmicContrast: 0.15419527996276128
purpose:
  - type: contact
    label: E-Mail me
    url: 'mailto:rbecker@prime-fit-121.de'
  - type: external
    label: Facebook
    url: 'https://www.facebook.com/primefit121/'
title: Medical Training/Athleten Coaching
description: Beseitigung von Dysbalancen orthopädischer Natur
author:
  name: Rene Becker
  email: rbecker@prime-fit-121.de
content_rating:
  adult: false
navigation:
  - name: Medical Fitness / PT
    id: b0bc4906-3d76-457d-8804-8e0560e09ed8
    type: content
  - name: Saison 2017
    id: cff959ae-89b1-4a93-9920-22ae4475ae0d
    type: content
  - name: Wir unterwegs
    id: 3e4fc9b1-5a3c-433b-b1b2-16bdd6d53cbd
    type: content
  - name: Impressum
    id: 5046d78d-1d08-4ab2-978a-b61a97f14d5c
    type: content
  - name: Systemvorstellung
    id: 1ef77893-5ec8-4dc8-bae2-b398df767af3
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
