name: PrimeFit
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/63aa34cf-9654-4cf6-b4a7-44c935b116e7.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d29573cd-33bc-4353-8131-be4143eb00a0.jpg
layout_spectrum: 0.874684969894588
typography_spectrum: 0.7190257837064564
analytics:
  twitter: Herr
opengraph:
  type: Medical Fitness
  appId: 'https://www.facebook.com/primefit121/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/faf835e1-ffec-489c-b494-6d0bf6a8ca47.jpg
color:
  brandColors:
    - '#000000'
    - '#808080'
    - '#FFFFFF'
    - '#C0C0C0'
    - '#333333'
  brandStrength: 0.2552195694297552
  lightness: 0.7874887136276811
  saturation: 0.2550325335469097
  rhythmicContrast: 0.22980797197669744
purpose:
  - type: contact
    label: E-Mail me
    url: 'mailto:rbecker@prime-fit-121.de'
  - type: external
    label: Facebook
    url: 'https://www.facebook.com/primefit121/'
title: Medical Training / Wettkampf Betreuung
description: Beseitigung von Dysbalancen orthopädischer Natur
author:
  name: Rene Becker
  email: rbecker@prime-fit-121.de
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15b7f98-c2b0-40ea-811b-357a1bd1ccef.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ebe35c4d-0969-44ab-93ac-21f2210d37f7.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
